# Generated by Django 4.1.1 on 2022-09-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='detect',
        ),
    ]
